import { getAllPainPoints, getPainPointStats } from '../storage/database.js';

/**
 * 生成每日报告
 */
export function generateDailyReport() {
  console.log('📝 生成每日报告...');
  
  const stats = getPainPointStats();
  const painPoints = getAllPainPoints(50);
  
  // 按来源分组
  const bySource = {};
  painPoints.forEach(pp => {
    if (!bySource[pp.source]) bySource[pp.source] = [];
    bySource[pp.source].push(pp);
  });
  
  const today = new Date().toISOString().split('T')[0];
  
  let report = `# 🎯 痛点雷达 - 每日报告
Generated: ${today}

---

## 📊 统计概览

| 指标 | 数量 |
|------|------|
| 总痛点数 | ${stats.total} |
| 待验证 | ${stats.byStatus.find(s => s.status === 'discovered')?.count || 0} |
| 已验证 | ${stats.byStatus.find(s => s.status === 'validated')?.count || 0} |
| 已交付 | ${stats.byStatus.find(s => s.status === 'shipped')?.count || 0} |

---

## 📰 来源分布

| 来源 | 数量 |
|------|------|
${stats.bySource.map(s => `| ${s.source} | ${s.count} |`).join('\n')}

---

## 🔥 最新发现 (Top 20)

${painPoints.slice(0, 20).map((pp, i) => `
### ${i + 1}. ${pp.conclusion.substring(0, 80)}${pp.conclusion.length > 80 ? '...' : ''}

- **来源**: ${pp.source}
- **链接**: ${pp.evidence_url}
- **行动**: ${pp.next_action}
- **状态**: ${pp.status}
- **日期**: ${pp.created_at}
`).join('\n')}

---

## 💡 建议行动

1. 审查今日发现的高热度痛点
2. 验证 2-3 个最有价值的痛点
3. 更新痛点状态

---

*Generated by Pain Point Radar*
`;
  
  console.log('✅ 报告生成完成');
  return report;
}

/**
 * 生成 JSON 格式报告
 */
export function generateJSONReport() {
  const stats = getPainPointStats();
  const painPoints = getAllPainPoints(100);
  
  return {
    generated_at: new Date().toISOString(),
    stats,
    pain_points: painPoints
  };
}

// 测试
// console.log(generateDailyReport());
